routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MotorcycleController;
use App\Http\Controllers\Auth\VerifyEmailController;
use App\Livewire\Admin\BrandList;
use Illuminate\Support\Facades\Route;
use Livewire\Volt\Volt;

Volt::route('login', 'admin.pages.auth.login')
    ->name('login')
    ->middleware('guest');

Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/brands', BrandList::class)->name('brands');

    Route::get('/motorcycles', [MotorcycleController::class, 'index'])->name('motorcycles');
    Route::get('/motorcycles/create', [MotorcycleController::class, 'create'])->name('motorcycles.create');
    Route::post('/motorcycles', [MotorcycleController::class, 'store']);
    Route::get('/motorcycles/{motorcycle:slug}', [MotorcycleController::class, 'edit'])->name('motorcycles.edit');
    Route::put('/motorcycles/{motorcycle:slug}', [MotorcycleController::class, 'update']);
    Route::delete('/motorcycles/{motorcycle:slug}', [MotorcycleController::class, 'destroy'])->name('motorcycles.delete');

    Route::get('/articles', [ArticleController::class, 'index'])->name('articles');
    Route::get('/articles/create', [ArticleController::class, 'create'])->name('articles.create');
    Route::post('/articles', [ArticleController::class, 'store']);
    Route::get('/articles/{article:slug}', [ArticleController::class, 'edit'])->name('articles.edit');
    Route::put('/articles/{article:slug}', [ArticleController::class, 'update']);
});


// Not Used
Route::middleware('guest')->group(function () {
    Volt::route('register', 'pages.auth.register')
        ->name('register');

    Volt::route('forgot-password', 'pages.auth.forgot-password')
        ->name('password.request');

    Volt::route('reset-password/{token}', 'pages.auth.reset-password')
        ->name('password.reset');
});

Route::middleware('auth')->group(function () {
    Volt::route('verify-email', 'pages.auth.verify-email')
        ->name('verification.notice');

    Route::get('verify-email/{id}/{hash}', VerifyEmailController::class)
        ->middleware(['signed', 'throttle:6,1'])
        ->name('verification.verify');

    Volt::route('confirm-password', 'pages.auth.confirm-password')
        ->name('password.confirm');
});

routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\MotorcycleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/', 'pages.home')->name('home');

Route::get('/{brand_slug}_{slug}', [MotorcycleController::class, 'show'])->name('motorcycles.show');

Route::get('/berita', [ArticleController::class, 'index'])->name('articles');
Route::get('/berita/{slug}', [ArticleController::class, 'show'])->name('articles.show');

Route::view('dashboard', 'dashboard')
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::view('profile', 'profile')
    ->middleware(['auth'])
    ->name('profile');

app/Models/Article.php
<?php

namespace App\Models;

use App\Traits\GenerateUniqueSlugTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Te7aHoudini\LaravelTrix\Traits\HasTrixRichText;

class Article extends Model
{
    use HasFactory, GenerateUniqueSlugTrait, HasTrixRichText;

    protected $guarded = [];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Article;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
    public function index(): View
    {
        return view('admin.article.index');
    }

    public function create(): View
    {
        $article = null;
        return view('admin.article.form', compact('article'));
    }

    public function store(Request $request): RedirectResponse
    {
        $data = $request->validate([
            'title' => 'required',
            'image' => ['required', 'image'],
            'article-trixFields' => 'required',
            'attachment-article-trixFields' => 'nullable',
            'publish' => 'required',
        ]);

        $data['image'] = $request->file('image')->storePublicly('articles');
        $data['slug'] = Str::slug($data['title']);
        $data['user_id'] = $request->user()->id;
        $data['is_publish'] = $data['publish'] === 'Submit';

        unset($data['publish']);
        Article::create($data);

        return redirect()
            ->route('admin.articles')
            ->with('success', 'Article Created Successfully');
    }

    public function edit(Article $article): View
    {
        return view('admin.article.form', compact('article'));
    }

    public function update(Article $article, Request $request): RedirectResponse
    {
        $data = $request->validate([
            'title' => 'required',
            'image' => ['image'],
            'article-trixFields' => 'required',
            'attachment-article-trixFields' => 'nullable',
            'publish' => 'required',
        ]);
        $data['slug'] = Str::slug($data['title']);
        $data['is_publish'] = $data['publish'] === 'Submit';

        if ($request->hasFile('image')) {
            $data['image'] = $request->file('image')->storePublicly('articles');
        }

        unset($data['publish']);
        $article->update($data);

        return redirect()
            ->route('admin.articles')
            ->with('success', 'Article Updated Successfully');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ArticleController
{
    public function index(Request $request): JsonResponse|View
    {
        if ($request->wantsJson()) {
            $articles = Article::with('user', 'trixRichText')
                ->where('is_publish', true)
                ->orderBy('id', 'desc')
                ->paginate(10);

            foreach ($articles as $article) {
                $article->image_url = $article->image ? Storage::url($article->image) : 'https://placehold.co/600x400';
                $article->excerpt = Str::limit(strip_tags($article->trixRichText->first()->content), 150);
                $article->post_date = $article->created_at->isToday() ? 'Hari ini' : indonesian_date($article->created_at);
            }

            return response()->json($articles);
        }

        return view('pages.article.index');
    }

    public function show(string $slug): View
    {
        $article = Article::with('user', 'trixRichText')
            ->where('slug', $slug)
            ->firstOrFail();

        return view('pages.article.show', compact('article'));
    }
}

app/Livewire/Admin/ArticleList.php
<?php

namespace App\Livewire\Admin;

use App\Models\Article;
use Illuminate\Contracts\View\View;
use Livewire\Component;
use Livewire\WithPagination;

class ArticleList extends Component
{
    use WithPagination;

    public function render(): View
    {
        $articles = Article::with('user')->paginate(10);
        return view('livewire.admin.pages.article-lists', compact('articles'));
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.admin');
    }
}

resources/views/admin/article/form.blade.php
<x-admin-layout>
    <div class="py-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800 dark:border-gray-700">
        <div class="w-full mb-1">
            <div class="mb-4 px-4">
                @if($article)
                    {{ Breadcrumbs::render('articles-edit', $article) }}
                    <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">Edit Article</h1>
                @else
                    {{ Breadcrumbs::render('articles-create') }}
                    <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">Create Article</h1>
                @endif
            </div>

            @if($article)
                <form class="px-4 relative bg-white rounded-lg dark:bg-gray-800" action="{{ route('admin.articles.edit', $article->slug) }}" method="post" enctype="multipart/form-data">
                    @csrf @method('put')
            @else
                <form class="px-4 relative bg-white rounded-lg dark:bg-gray-800" action="{{ route('admin.articles') }}" method="post" enctype="multipart/form-data">
                    @csrf
            @endif
                    <div class="grid grid-cols-6 gap-6">
                        <div class="col-span-6 sm:col-span-3">
                            <label for="title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title</label>
                            <input type="text" name="title" id="title" value="{{ $article?->title ?? old('title') }}" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Article Title" required>
                        </div>
                        <div class="col-span-12 sm:col-span-12">
                            <label for="image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Image</label>
                            <input type="file" accept="image/*" name="image" id="image" class="block max-w-md w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" {{ $article ? '' : 'required' }}>
                        </div>
                        <div class="mt-1 col-span-12 sm:col-span-12">
                            @if ($article)
                                {!! $article->trix('content') !!}
                            @else
                                @trix(\App\Models\Article::class, 'content')
                            @endif
                        </div>
                    </div>

                    <div class="items-center mt-6">
                        <input type="submit" name="publish" value="Submit" class="text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center hover:cursor-pointer dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" />
                        <input type="submit" name="publish" value="Save as Draft" class="ml-1 hover:cursor-pointer text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" />
                    </div>
                </form>
        </div>
    </div>
</x-admin-layout>

resources/views/admin/article/index.blade.php
<x-admin-layout>
    <div class="py-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800 dark:border-gray-700">
        <div class="w-full mb-1">
            <div class="mb-4 px-4">
                {{ Breadcrumbs::render('articles') }}
                <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">All Articles</h1>
            </div>

            <livewire:admin.article-list />
        </div>
    </div>
</x-admin-layout>